# Generated by Django 5.0.6 on 2024-06-18 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGroup',
            fields=[
                ('TGID', models.AutoField(primary_key=True, serialize=False)),
                ('TGCategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TravelStyle',
            fields=[
                ('TSID', models.AutoField(primary_key=True, serialize=False)),
                ('Theme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('Country', 'City')},
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('PlanID', models.AutoField(primary_key=True, serialize=False)),
                ('destination_country', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_plan.travelgroup')),
                ('travel_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_plan.travelstyle')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ActivityID', models.AutoField(primary_key=True, serialize=False)),
                ('Duration', models.DurationField()),
                ('PlanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_plan.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('AccommodationID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=100)),
                ('PriceRange', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=100)),
                ('PlanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_plan.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.TextField()),
                ('Rating', models.IntegerField()),
                ('PlanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_plan.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('TransportationID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=100)),
                ('Origin', models.CharField(max_length=100)),
                ('Destination', models.CharField(max_length=100)),
                ('Duration', models.DurationField()),
                ('EstimatedCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PlanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_plan.plan')),
            ],
        ),
    ]
